package fr.jhelp.tools.engine3d.resources.texture

import fr.jhelp.tools.engine3d.scene.Texture

/**
 * Source where get a texture
 */
sealed class TextureSource<T:Texture>
{
    /** Texture generated by the source */
    val texture: T by lazy { this.createTexture() }

    /** Create a texture from the source */
    protected abstract fun createTexture(): T
}
